<a href="https://colab.research.google.com/github/sofiane1010/SIC_checkpoints/blob/main/exercises/1_NumPy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# NumPy exercises


In [ ]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.19.5


### Create a numpy array of size 10, filled with zeros.

In [ ]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])



### Create a numpy array with values ranging from 10 to 49

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])



### Create a numpy matrix of 2*2 integers, filled with ones.

In [ ]:
np.ones((2,2), dtype=int)

array([[1, 1],
       [1, 1]])



### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [ ]:
np.ones((3,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])



### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [ ]:
X = np.random.random(4)
np.ones(X.shape, dtype=int)

array([1, 1, 1, 1])



### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [ ]:
X = np.random.random((4, 4))
np.zeros(X.shape, dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])



### Create a numpy matrix of 4*4 integers, filled with fives.

In [ ]:
np.ones((4,4), dtype=int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])



### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [ ]:
np.ones(X.shape, dtype=int) * 7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])



### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [ ]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])



### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [ ]:
np.random.randint(1,11,size=3)

array([ 1,  3, 10])



### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [ ]:
np.random.random((3,3,3))

array([[[9.76645847e-01, 7.95719490e-01, 9.71558274e-01],
        [1.53811236e-01, 7.08998197e-01, 6.29896442e-01],
        [3.46385014e-01, 4.75243875e-01, 3.14479226e-01]],

       [[7.70113023e-01, 9.62005215e-01, 8.09001986e-01],
        [4.05809026e-04, 1.21020212e-02, 3.33602961e-01],
        [1.29798297e-01, 8.96041323e-01, 8.66039069e-01]],

       [[3.03083932e-01, 4.76471362e-01, 8.42471523e-01],
        [3.68832996e-01, 8.19968215e-02, 6.49604442e-01],
        [3.51869889e-01, 4.71744970e-01, 6.77474969e-01]]])



### Given the X python list convert it to an Y numpy array

In [ ]:
X = [1,2,3,4]
Y = np.array(X)
Y

array([1, 2, 3, 4])



### Given the X numpy array, make a copy and store it on Y.

In [ ]:
X = np.array([1,2,3,4])
Y = np.copy(X)
Y

array([1, 2, 3, 4])



### Create a numpy array with numbers from 1 to 10

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])



### Create a numpy array with the odd numbers between 1 to 10

In [ ]:
np.arange(1,11, step=2)

array([1, 3, 5, 7, 9])



### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])



### Show the memory size of the given Z numpy matrix

In [ ]:
Z = np.arange(9).reshape(3,3)
print("The memory size of one element of the matrix:", Z.itemsize)
print("The size of the matrix (or the number of elements of the matrix", Z.size)
print("Therefore, the memory size of the matrix Z is:", Z.itemsize * Z.size, "bytes")

The memory size of one element of the matrix: 8
The size of the matrix (or the number of elements of the matrix 9
Therefore, the memory size of the matrix Z is: 72 bytes


### Given the X numpy array, show it's first element

In [ ]:
X = np.array([1,2,3,4])
print(X)
X[0]

[1 2 3 4]


1



### Given the X numpy array, show it's last element

In [ ]:
print(X)
X[- 1]

[1 2 3 4]


4



### Given the X numpy array, show it's first three elements

In [ ]:
print(X)
X[:3]

[1 2 3 4]


array([1, 2, 3])



### Create a numpy array with numbers from 1 to 10, in descending order.

In [ ]:
X = np.array([2,5,4,1,3,8,7,9,10,6])
np.sort(X)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])



### Given the X numpy array, show all middle elements

In [ ]:
# your code goes here
def get_middle(arr):
    shape = arr.shape[0]
    if shape%2:
        return arr[int(shape/2),int(shape/2)]
    return arr[int(shape/2)-1:int(shape/2)+1, int(shape/2)-1:int(shape/2)+1]

X = np.arange(36).reshape(6,6)
Y = np.arange(25).reshape(5,5)

print("For a matrix with even dimensions:")
print(X)
print("")
print("The middle elements are:")
print(get_middle(X))
print("")
print("For a matrix with odd dimensions:")
print(Y)
print("")
print("The middle elements are:")
print(get_middle(Y))
print("")

For a matrix with even dimensions:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

The middle elements are:
[[14 15]
 [20 21]]

For a matrix with odd dimensions:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The middle elements are:
12





### Given the X numpy array, show the elements in reverse position

In [ ]:
X = np.array([3,5,2,6,8])
print("initial array:",X)
print("updated array:",np.flip(X))

initial array: [3 5 2 6 8]
updated array: [8 6 2 5 3]




### Given the X numpy array, show the elements in an odd position

In [ ]:
X = np.array([8,8,3,4,5,3,5,3,2])
print(X)
print(X[::2])

[8 8 3 4 5 3 5 3 2]
[8 3 5 5 2]




### Given the X numpy matrix, show the first row elements

In [ ]:
X = np.arange(16).reshape(4,4)
print(X)
X[0]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([0, 1, 2, 3])



### Given the X numpy matrix, show the last row elements

In [ ]:
X = np.arange(16).reshape(4,4)
print(X)
print("last row elements:",X[-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
last row elements: [12 13 14 15]




### Given the X numpy matrix, show the first element on first row

In [ ]:
X = np.arange(16).reshape(4,4)
print(X)
print("first elements of the first row:",X[0,0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
first elements of the first row: 0




### Given the X numpy matrix, show the last element on last row

In [ ]:
X = np.arange(16).reshape(4,4)
print(X)
print("last element on last row:",X[-1,-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
last element on last row: 15




### Given the X numpy matrix, show the middle row elements

In [ ]:
X = np.arange(25).reshape(5,5)
Y = np.arange(16).reshape(4,4)

def mid_row(arr):
    shape = arr.shape[0]
    if shape%2:
        return arr[int(shape/2)]
    return arr[int(shape/2)-1:int(shape/2)+1]

print("for a matrix with even dimensions")
print(X)
print("")
print("the middle row is:")
print(mid_row(X))
print("")
print("for a matrix with odd dimensions")
print(Y)
print("")
print("the middle rows are:")
print(mid_row(Y))


for a matrix with even dimensions
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

the middle row is:
[10 11 12 13 14]

for a matrix with odd dimensions
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

the middle rows are:
[[ 4  5  6  7]
 [ 8  9 10 11]]




### Given the X numpy matrix, show the first two elements on the first two rows

In [ ]:
print(X)
print("")
print("the first two elements on the first rwo rows:")
print("")
print(X[:2,:2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

the first two elements on the first rwo rows:

[[0 1]
 [5 6]]




### Given the X numpy matrix, show the last two elements on the last two rows

In [ ]:
print(X)
print('')
print("the last two elements on the last two rows:")
print('')
X[-2:,-2:]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

the last two elements on the last two rows:



array([[18, 19],
       [23, 24]])

### Convert the given integer numpy array to float

In [ ]:
X = np.arange(9, dtype=int)
X.astype(np.float32)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)



### Reverse the given numpy array (first element becomes last)

In [ ]:
X = np.array([3,4,2,6,8])
np.flip(X)

array([8, 6, 2, 4, 3])



### Order (sort) the given numpy array

In [ ]:
print("initial array:")
print(X)
print("sorted array (ascendent sorting):")
print(np.sort(X))

initial array:
[3 4 2 6 8]
sorted array (ascendent sorting):
[2 3 4 6 8]




### Given the X numpy array, set the fifth element equal to 1

In [ ]:
print(X)
X[4] = 1
print(X)

[3 4 2 6 8]
[3 4 2 6 1]




### Given the X numpy array, change the 50 with a 40

In [ ]:
X = np.array([3,4,2,50,8,50,6])
print(X)
X[X==50] = 40
print(X)


[ 3  4  2 50  8 50  6]
[ 3  4  2 40  8 40  6]



### Given the X numpy matrix, change the last row with all 1

In [ ]:
X = np.arange(9).reshape(3,3)
print(X)
X[-1] = 1
print(" ")
print(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[0 1 2]
 [3 4 5]
 [1 1 1]]



### Given the X numpy matrix, change the last item on the last row with a 0

In [ ]:
X = np.arange(9).reshape(3,3)
print(X)
X[-1,-1] = 0
print("")
print(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2]
 [3 4 5]
 [6 7 0]]



### Given the X numpy matrix, add 5 to every element

In [ ]:
X = np.arange(9).reshape(3,3)
print("initial matrix:")
print('')
print(X)
print('')
print("updated matrix:")
print('')
print(X+5)

initial matrix:

[[0 1 2]
 [3 4 5]
 [6 7 8]]

updated matrix:

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]



## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [ ]:
def get_neg(arr):
  return arr[arr<0]

In [ ]:
X = np.random.randint(-5, 5, 5)
print(X)
print(get_neg(X))

[ 1 -4  1  3 -4]
[-4 -4]



### Given the X numpy array, get the negative elements

In [ ]:
print(X)
print(get_neg(X))

[ 1 -4  1  3 -4]
[-4 -4]



### Given the X numpy array, get numbers higher than 5

In [ ]:
X = np.random.randint(0, 10, 5)
print(X)
print(X[X > 5])

[4 8 0 0 8]
[8 8]



### Given the X numpy array, get numbers higher than the elements mean

In [ ]:
print(X)
print("mean:",X.mean())
print(X[X > X.mean()])

[4 8 0 0 8]
mean: 4.0
[8 8]



### Given the X numpy array, get numbers equal to 2 or 10

In [ ]:
X = np.array([3,5,2,3,7,8,10,10])
print(X)
print(X[(X == 2) | (X == 10)])

[ 3  5  2  3  7  8 10 10]
[ 2 10 10]



## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [ ]:
X = np.random.randint(-5,5,8)
print(X)
print(all(X != 0))

[-5  2 -4  2  1  2 -5  4]
True



## Summary statistics

### Given the X numpy array, show the sum of its elements

In [ ]:
X = np.arange(4)
print(X)
print(X.sum())

[0 1 2 3]
6



### Given the X numpy array, show the mean value of its elements

In [ ]:
X = np.arange(9)
print(X)
print(X.mean())

[0 1 2 3 4 5 6 7 8]
4.0



### Given the X numpy matrix, show the sum of its columns

In [ ]:
X = np.arange(9).reshape(3,3)
print(X)
print("sum:",X.sum(axis=0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
sum: [ 9 12 15]



### Given the X numpy matrix, show the mean value of its rows

In [ ]:
print(X)
print("sum:",X.mean(axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
sum: [1. 4. 7.]


### Given the X numpy array, show the max value of its elements

In [ ]:
print(X)
print("sum:",X.max())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
sum: 8


# Answer The following questions!

In [ ]:
import seaborn as sns

In [ ]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'tips',
 'titanic']

In [ ]:
df = sns.load_dataset('titanic')

In [ ]:
df.head(20)

survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0          0       3    male  22.0  ...   NaN  Southampton     no  False
1          1       1  female  38.0  ...     C    Cherbourg    yes  False
2          1       3  female  26.0  ...   NaN  Southampton    yes   True
3          1       1  female  35.0  ...     C  Southampton    yes  False
4          0       3    male  35.0  ...   NaN  Southampton     no   True
5          0       3    male   NaN  ...   NaN   Queenstown     no   True
6          0       1    male  54.0  ...     E  Southampton     no   True
7          0       3    male   2.0  ...   NaN  Southampton     no  False
8          1       3  female  27.0  ...   NaN  Southampton    yes  False
9          1       2  female  14.0  ...   NaN    Cherbourg    yes  False
10         1       3  female   4.0  ...     G  Southampton    yes  False
11         1       1  female  58.0  ...     C  Southampton    yes   True
12         0       3    male  20.0  ...   NaN  Southampton     no   True
13         0       3    male  39.0  ...   NaN  Southampton     no  False
14         0       3  female  14.0  ...   NaN  Southampton     no   True
15         1       2  female  55.0  ...   NaN  Southampton    yes   True
16         0       3    male   2.0  ...   NaN   Queenstown     no  False
17         1       2    male   NaN  ...   NaN  Southampton    yes   True
18         0       3  female  31.0  ...   NaN  Southampton     no  False
19         1       3  female   NaN  ...   NaN    Cherbourg    yes   True

[20 rows x 15 columns]

As we can notice, there are a lot NaN values in the deck column as well as the age column. Let's get some more specific information

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


We can see that the that nearly 700 instances have their deck attribute missing. Therefore, it is not interesting to drop all those instances since they represent more than 75% of our data-set. Instead, we will replace the missing data. Since the deck attribute is a categorical one, we will replace the missing values by the most frequent ones.

In [ ]:
df.deck.value_counts()

C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: deck, dtype: int64

As we can see, the "C" attribute is the most frequent one, we will be replacing the missing deck attributes by it.

In [ ]:
df.deck.fillna('C', inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         891 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


Now that we have all missing deck attributes replaced, we can notice three other incomplet attributes: age, embarked and embark_town. Since there are only two missing values for the embarked and the embark_town, we will just delete their instances. However, for the age, we will replace by the mean value.


In [ ]:
# replacing the age by the mean age
women = df.who=='woman'
df.age.fillna(df.age.mean(), inplace=True)

# deleting the instances with missing umbarked and umbark_town
df.dropna(how='any', inplace=True)
df.info()




<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     889 non-null    int64   
 1   pclass       889 non-null    int64   
 2   sex          889 non-null    object  
 3   age          889 non-null    float64 
 4   sibsp        889 non-null    int64   
 5   parch        889 non-null    int64   
 6   fare         889 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        889 non-null    category
 9   who          889 non-null    object  
 10  adult_male   889 non-null    bool    
 11  deck         889 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        889 non-null    object  
 14  alone        889 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 87.3+ KB


# Average age of woman category.

In [ ]:
df[df.who=='woman'].age.mean()

31.412837305926107

## Average age of man category.

In [ ]:
df[df.who=='man'].age.mean()

32.37093219410664

## The lowest age among alone woman.

In [ ]:
df[(df.alone==False) & (df.who=="woman")].age.min()

16.0

# Sort the DataFrame in ascending order of the 'age' use sort values (df.sort_values(by='...', ascending=...)). 

In [ ]:
df.sort_values(by='age', ascending=True)

survived  pclass     sex    age  ...  deck  embark_town  alive  alone
803         1       3    male   0.42  ...     C    Cherbourg    yes  False
755         1       2    male   0.67  ...     C  Southampton    yes  False
469         1       3  female   0.75  ...     C    Cherbourg    yes  False
644         1       3  female   0.75  ...     C    Cherbourg    yes  False
831         1       2    male   0.83  ...     C  Southampton    yes  False
..        ...     ...     ...    ...  ...   ...          ...    ...    ...
116         0       3    male  70.50  ...     C   Queenstown     no   True
493         0       1    male  71.00  ...     C    Cherbourg     no   True
96          0       1    male  71.00  ...     A    Cherbourg     no   True
851         0       3    male  74.00  ...     C  Southampton     no   True
630         1       1    male  80.00  ...     A  Southampton    yes   True

[889 rows x 15 columns]